image: node:4.2.2
cache:
  paths:
  - node_modules/
stages:
  - stage1
stage1job:
   stage: stage1
   script: 
     - cd the-example-app.nodejs
     - npm install
     - node ./app.js
   tags:
     - gitlab-org

