image: node:11.15.0
cache:
  paths:
  - ./the-example-app.nodejs/node_modules/
stages:
  - stage1
stage1job:
   stage: stage1
   script: 
     - cd the-example-app.nodejs
     - npm install
     - ls -al
     - node ./app.js
   tags:
     - gitlab-org

